const gitUser = {
  "login": "Dongyeon915",
  "id": 109599149,
  "node_id": "U_kgDOBohZrQ",
  "avatar_url": "https://avatars.githubusercontent.com/u/109599149?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Dongyeon915",
  "html_url": "https://github.com/Dongyeon915",
  "followers_url": "https://api.github.com/users/Dongyeon915/followers",
  "following_url": "https://api.github.com/users/Dongyeon915/following{/other_user}",
  "gists_url": "https://api.github.com/users/Dongyeon915/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Dongyeon915/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Dongyeon915/subscriptions",
  "organizations_url": "https://api.github.com/users/Dongyeon915/orgs",
  "repos_url": "https://api.github.com/users/Dongyeon915/repos",
  "events_url": "https://api.github.com/users/Dongyeon915/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Dongyeon915/received_events",
  "type": "User",
  "site_admin": false,
  "name": "AbDul",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 9,
  "public_gists": 0,
  "followers": 1,
  "following": 1,
  "created_at": "2022-07-19T12:38:37Z",
  "updated_at": "2023-02-25T05:52:21Z"
}
export default gitUser